name: Cypress Tests

on: [ push ]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run --env email=${{ secrets.EMAIL }},password=${{ secrets.PASSWORD }}